[2023-06-21 16:31:36,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-21 16:31:36,606] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-21 16:31:36,606] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:31:36,607] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-21 16:31:36,607] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:31:36,620] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-06-12 00:00:00+00:00
[2023-06-21 16:31:36,624] {standard_task_runner.py:52} INFO - Started process 10439 to run task
[2023-06-21 16:31:36,627] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpjqnzwugr', '--error-file', '/tmp/tmpfsy_j8g2']
[2023-06-21 16:31:36,628] {standard_task_runner.py:80} INFO - Job 92: Subtask extrai_dados
[2023-06-21 16:31:36,662] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [running]> on host alura
[2023-06-21 16:31:36,705] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-12T00:00:00+00:00
[2023-06-21 16:31:37,299] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gilmar/Documentos/airflowalura/dags/dados_climaticos.py", line 31, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'home/millenagena/Documents/airflowalura/semana=2023-06-19'
[2023-06-21 16:31:37,306] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230612T000000, start_date=20230621T193136, end_date=20230621T193137
[2023-06-21 16:31:37,314] {standard_task_runner.py:92} ERROR - Failed to execute job 92 for task extrai_dados (Cannot save file into a non-existent directory: 'home/millenagena/Documents/airflowalura/semana=2023-06-19'; 10439)
[2023-06-21 16:31:37,330] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-21 16:31:37,345] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-22 10:14:16,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-22 10:14:16,287] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-22 10:14:16,287] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:14:16,288] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-22 10:14:16,288] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:14:16,300] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-06-12 00:00:00+00:00
[2023-06-22 10:14:16,303] {standard_task_runner.py:52} INFO - Started process 7260 to run task
[2023-06-22 10:14:16,305] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkq4yudlx', '--error-file', '/tmp/tmpr64is4gr']
[2023-06-22 10:14:16,306] {standard_task_runner.py:80} INFO - Job 141: Subtask extrai_dados
[2023-06-22 10:14:16,339] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [running]> on host alura
[2023-06-22 10:14:16,380] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-12T00:00:00+00:00
[2023-06-22 10:14:17,224] {python.py:173} INFO - Done. Returned value was: None
[2023-06-22 10:14:17,229] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230612T000000, start_date=20230622T131416, end_date=20230622T131417
[2023-06-22 10:14:17,260] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-22 10:14:17,276] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-22 10:19:00,464] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-22 10:19:00,471] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-22 10:19:00,471] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:19:00,471] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-22 10:19:00,471] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:19:00,480] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-06-12 00:00:00+00:00
[2023-06-22 10:19:00,484] {standard_task_runner.py:52} INFO - Started process 9075 to run task
[2023-06-22 10:19:00,487] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpt99nfbfw', '--error-file', '/tmp/tmptjtsliku']
[2023-06-22 10:19:00,488] {standard_task_runner.py:80} INFO - Job 158: Subtask extrai_dados
[2023-06-22 10:19:00,522] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-06-12T00:00:00+00:00 [running]> on host alura
[2023-06-22 10:19:00,557] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-12T00:00:00+00:00
[2023-06-22 10:19:01,277] {python.py:173} INFO - Done. Returned value was: None
[2023-06-22 10:19:01,284] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230612T000000, start_date=20230622T131900, end_date=20230622T131901
[2023-06-22 10:19:01,312] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-22 10:19:01,327] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
