[2023-06-21 16:29:39,561] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2023-06-21 16:29:39,566] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2023-06-21 16:29:39,566] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:29:39,566] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-21 16:29:39,566] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:29:39,575] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2023-06-21 16:29:39,579] {standard_task_runner.py:52} INFO - Started process 9691 to run task
[2023-06-21 16:29:39,582] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos_OLD.py', '--cfg-path', '/tmp/tmph7l68355', '--error-file', '/tmp/tmplvc8soao']
[2023-06-21 16:29:39,582] {standard_task_runner.py:80} INFO - Job 87: Subtask cria_pasta
[2023-06-21 16:29:39,621] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alura
[2023-06-21 16:29:39,643] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-06-21 16:29:39,647] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20230621T192939, end_date=20230621T192939
[2023-06-21 16:29:39,657] {standard_task_runner.py:92} ERROR - Failed to execute job 87 for task cria_pasta (unexpected end of template, expected ','.; 9691)
[2023-06-21 16:29:39,677] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-21 16:29:39,705] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-21 16:31:19,145] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2023-06-21 16:31:19,150] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2023-06-21 16:31:19,150] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:31:19,150] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-21 16:31:19,150] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:31:19,161] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2023-06-21 16:31:19,164] {standard_task_runner.py:52} INFO - Started process 10298 to run task
[2023-06-21 16:31:19,167] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpvgra9hd2', '--error-file', '/tmp/tmpzi0puesk']
[2023-06-21 16:31:19,168] {standard_task_runner.py:80} INFO - Job 84: Subtask cria_pasta
[2023-06-21 16:31:19,199] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alura
[2023-06-21 16:31:19,230] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2023-06-21 16:31:19,231] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-21 16:31:19,231] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/gilmar/Documentos/airflowalura/semana=2022-11-21"']
[2023-06-21 16:31:19,241] {subprocess.py:85} INFO - Output:
[2023-06-21 16:31:19,243] {subprocess.py:96} INFO - Command exited with return code 0
[2023-06-21 16:31:19,261] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20230621T193119, end_date=20230621T193119
[2023-06-21 16:31:19,304] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-21 16:31:19,324] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-06-22 10:19:10,585] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2023-06-22 10:19:10,594] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2023-06-22 10:19:10,594] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:19:10,594] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-22 10:19:10,594] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:19:10,605] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2023-06-22 10:19:10,608] {standard_task_runner.py:52} INFO - Started process 9159 to run task
[2023-06-22 10:19:10,611] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkuuiuxq2', '--error-file', '/tmp/tmp4l478psl']
[2023-06-22 10:19:10,611] {standard_task_runner.py:80} INFO - Job 162: Subtask cria_pasta
[2023-06-22 10:19:10,649] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host alura
[2023-06-22 10:19:10,706] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2023-06-22 10:19:10,707] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-22 10:19:10,707] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/gilmar/Documentos/airflowalura/semana=2022-11-21"']
[2023-06-22 10:19:10,726] {subprocess.py:85} INFO - Output:
[2023-06-22 10:19:10,726] {subprocess.py:96} INFO - Command exited with return code 0
[2023-06-22 10:19:10,746] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20230622T131910, end_date=20230622T131910
[2023-06-22 10:19:10,789] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-22 10:19:10,816] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
