[2023-06-21 16:29:36,629] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2023-06-21 16:29:36,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2023-06-21 16:29:36,633] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:29:36,633] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-21 16:29:36,633] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:29:36,643] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2023-06-21 16:29:36,647] {standard_task_runner.py:52} INFO - Started process 9667 to run task
[2023-06-21 16:29:36,650] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos_OLD.py', '--cfg-path', '/tmp/tmp2bb7edk7', '--error-file', '/tmp/tmpzod3kw66']
[2023-06-21 16:29:36,651] {standard_task_runner.py:80} INFO - Job 86: Subtask cria_pasta
[2023-06-21 16:29:36,685] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alura
[2023-06-21 16:29:36,705] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/gilmar/Documentos/airflowalura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-06-21 16:29:36,710] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20230621T192936, end_date=20230621T192936
[2023-06-21 16:29:36,721] {standard_task_runner.py:92} ERROR - Failed to execute job 86 for task cria_pasta (unexpected end of template, expected ','.; 9667)
[2023-06-21 16:29:36,747] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-21 16:29:36,770] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-21 16:31:15,091] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2023-06-21 16:31:15,095] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2023-06-21 16:31:15,095] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:31:15,095] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-21 16:31:15,095] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-21 16:31:15,104] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2023-06-21 16:31:15,109] {standard_task_runner.py:52} INFO - Started process 10265 to run task
[2023-06-21 16:31:15,112] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpqp_l7n75', '--error-file', '/tmp/tmp9y1r4mej']
[2023-06-21 16:31:15,113] {standard_task_runner.py:80} INFO - Job 82: Subtask cria_pasta
[2023-06-21 16:31:15,144] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alura
[2023-06-21 16:31:15,179] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-07T00:00:00+00:00
[2023-06-21 16:31:15,180] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-21 16:31:15,181] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/gilmar/Documentos/airflowalura/semana=2022-11-14"']
[2023-06-21 16:31:15,188] {subprocess.py:85} INFO - Output:
[2023-06-21 16:31:15,191] {subprocess.py:96} INFO - Command exited with return code 0
[2023-06-21 16:31:15,208] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20230621T193115, end_date=20230621T193115
[2023-06-21 16:31:15,248] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-21 16:31:15,278] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-06-22 10:19:08,726] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2023-06-22 10:19:08,736] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2023-06-22 10:19:08,736] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:19:08,736] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-22 10:19:08,736] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-22 10:19:08,746] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-07 00:00:00+00:00
[2023-06-22 10:19:08,749] {standard_task_runner.py:52} INFO - Started process 9141 to run task
[2023-06-22 10:19:08,752] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmplcagjoo6', '--error-file', '/tmp/tmpb5jxma04']
[2023-06-22 10:19:08,753] {standard_task_runner.py:80} INFO - Job 161: Subtask cria_pasta
[2023-06-22 10:19:08,788] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-07T00:00:00+00:00 [running]> on host alura
[2023-06-22 10:19:08,830] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-07T00:00:00+00:00
[2023-06-22 10:19:08,831] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-22 10:19:08,832] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/gilmar/Documentos/airflowalura/semana=2022-11-14"']
[2023-06-22 10:19:08,840] {subprocess.py:85} INFO - Output:
[2023-06-22 10:19:08,844] {subprocess.py:96} INFO - Command exited with return code 0
[2023-06-22 10:19:08,861] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221107T000000, start_date=20230622T131908, end_date=20230622T131908
[2023-06-22 10:19:08,888] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-22 10:19:08,912] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
